spring:
  profiles:
    active:
    - local
    group:
      local: "site-local,db-local"
      dev: "site-dev,db-dev"
    include:
    - db
    - site
  banner:
    image:
      bitdepth: 8
      width: 100
      height: 15
  jpa:
    hibernate:
      use-new-id-generator-mappings: "false"
  mvc:
    static-path-pattern: "/resources/**" # 기본설정:/**
  messages:
    basename: "classpath:/messages"
logging:
#  file:
#    name: app.log
#    path: logs
  level:
    '[org.springframework.web]': DEBUG