spring:
  profiles:
    active:
    - local
    group:
      local: "site-local,db-local,my-service"
      dev: "site-dev"
    include:
    - db
    - site
    - my-service
  main:
    banner-mode: off
  banner:
    image:
      bitdepth: 8
      width: 100
      height: 15