spring:
  profiles:
    active:
    - local
    group:
      local: "site-local,db-local,my-service"
      dev: "site-dev"
    include:
    - db
    - site
    - my-service
  banner:
    image:
      bitdepth: 8
      width: 100
      height: 15
  jpa:
    hibernate:
      use-new-id-generator-mappings: "false"
logging:
  level:
    '[org.springframework.web]': DEBUG